#Author: Trevor Martin                                                       
#Date of Completion: ?                                                        
#Language: C                                                                  
#Class: CSCI241 | Systems Programming | Oberlin College                       
#Homework#: 1, Makefile                                                      
#===========================================================             
#target: dependencies                                                          
#       action                                                                       
all:hello rot128 diamond

hello:hello.c
        gccx -o hello hello.c

rot128:rot128.c
        gccx -o rot128 rot128.c

diamond:diamond.c
        gccx -o diamond diamond.c

clean:
        rm -f hello rot128 diamond


