#Author: Trevor Martin#
#Date of Completion: ?
#Language: C
#Homework #: 1, Makefile
#Class: CSCI241 | Systems Programming | Oberlin College
#===========================================================

#target: dependencies
#	action

all: hello

hello: hello.o
	clang hello.o -o hello -l m

hello.o: hello.c
	clang -c hello.c




